name: Linting

on: [push]

jobs:
  lint:
    name: Static code analysis / Linting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: npm install
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        npm install
    - name: Linting
      run: npx run-p check:*
